---
- hosts: all
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: keys/id_rsa
    postdeploy_image: "{{ lookup('env', 'POSTDEPLOY_IMAGE') }}"
    postdeploy_command: "{{ lookup('env', 'POSTDEPLOY_COMMAND') }}"

  tasks:
    - name: Add docker compose file
      copy:
        src: "{{ compose_file }}"
        dest: "/{{ compose_file }}"

    - name: Deploy docker stack
      shell: docker stack deploy --with-registry-auth -c /{{ compose_file }} {{ resource_prefix }}
      environment:
        AWS_ACCESS_KEY: "{{ aws_access_key }}"
        AWS_SECRET_KEY: "{{ aws_secret_key }}"
        STAGE: "{{ stage }}"
        RESOURCE_PREFIX: "{{ resource_prefix }}"
        STACK_HOSTNAME: "{{ stack_hostname }}"
        CI_COMMIT_REF_SLUG: "{{ lookup('env', 'CI_COMMIT_REF_SLUG') }}"
        CI_PROJECT_REGISTRY: "{{ lookup('env', 'CI_PROJECT_REGISTRY') }}"

    - name: Execute post deploy
      shell: >
        docker pull {{ postdeploy_image }};
        docker run
        --env AWS_ACCESS_KEY
        --env AWS_SECRET_KEY
        --network={{ resource_prefix }}_default
        --rm
        -ti
        {{ postdeploy_image }}
        {{ postdeploy_command }}
      environment:
        AWS_ACCESS_KEY: "{{ aws_access_key }}"
        AWS_SECRET_KEY: "{{ aws_secret_key }}"
        STAGE: "{{ stage }}"
        RESOURCE_PREFIX: "{{ resource_prefix }}"
        STACK_HOSTNAME: "{{ stack_hostname }}"
        CI_COMMIT_REF_SLUG: "{{ lookup('env', 'CI_COMMIT_REF_SLUG') }}"
        CI_PROJECT_REGISTRY: "{{ lookup('env', 'CI_PROJECT_REGISTRY') }}"

    - name: Remove docker compose file
      file:
        state: absent
        path: "/{{ compose_file }}"