---
- hosts: all
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: keys/id_rsa

  tasks:
    #- name: Create docker volume
    #  shell: "docker volume create --name={{ item.name }} --opt=size={{ item.size }} --driver={{ item.driver }}"
    #  with_items: "{{ volumes }}"

    #- name: Create docker objectstore volume
    #  shell: "docker volume create --name={{ stack_name }}-objectstore --opt=size=10 --driver=rexray/dobs"

    - name: Add docker compose file
      copy:
        src: docker-compose.yml
        dest: /docker-compose.yml

    - name: Deploy docker stack
      shell: docker stack deploy --with-registry-auth -c /docker-compose.yml {{ stack_name }}
      environment:
        STACK_NAME: "{{ stack_name }}"
        STACK_DOMAIN: "{{ stack_name }}.staging.sephton.io"

    - name: Remove docker compose file
      file:
        state: absent
        path: /docker-compose.yml