---
- hosts: $POSTGRES_HOST
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    postgres_database_name: "{{ resource_prefix }}-database"
    postgres_database_username: "{{ resource_prefix }}-user"
    postgres_database_password: "$POSTGRES_PASSWORD"

  tasks:
    - name: Create database user
      postgresql_user:
        name: "{{ postgres_database_username }}"
        password: "{{ postgres_database_password }}"
      become: true
      become_user: postgres
      when:
        - postgres_database_name != ""
        - postgres_database_username != ""
        - postgres_database_password != ""

    - name: Create database
      postgresql_db:
        name: "{{ postgres_database_name }}"
        owner: "{{ postgres_database_username }}"
      become: true
      become_user: postgres
      when:
        - postgres_database_name != ""
        - postgres_database_username != ""
        - postgres_database_password != ""

    # Required to avoid 'must be owner of schema public' errors on restore.
    - name: Set database public schema owner to created user
      postgresql_schema:
        database: "{{ postgres_database_name }}"
        name: public
        owner: "{{ postgres_database_username }}"
      become_user: postgres

    # Required to avoid 'must be owner of extension plpgsql' errors on restore.
    - name: Remove plpgsql extension from database
      postgresql_ext:
        db: "{{ postgres_database_name }}"
        name: plpgsql
        state: absent
      become_user: postgres

    - name: Restore database
      shell: /home/postgres_restore/bin/postgres_restore.sh
      environment:
        POSTGRES_RESTORE_SOURCE: "$POSTGRES_RESTORE_SOURCE"
        POSTGRES_HOST: "$POSTGRES_HOST"
        POSTGRES_NAME: "{{ postgres_database_name }}"
        POSTGRES_USER: "{{ postgres_database_username }}"
        POSTGRES_PASSWORD: "{{ postgres_database_password }}"
      become_user: postgres_restore

- hosts: $MINIO_HOST
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    minio_bucket_name: "{{ resource_prefix }}-bucket"
    minio_access_key: "{{ resource_prefix }}-user"
    minio_secret_key: "$MINIO_SECRET_KEY"

  tasks:
    - name: Add objectstore user policy definition
      copy:
        content: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetBucketLocation",
                  "s3:ListBucket",
                  "s3:ListBucketMultipartUploads"
                ],
                "Resource": [
                  "arn:aws:s3:::{{ minio_bucket_name }}"
                ],
                "Sid": ""
              },
              {
                "Effect": "Allow",
                "Action": [
                  "s3:AbortMultipartUpload",
                  "s3:DeleteObject",
                  "s3:GetObject",
                  "s3:ListMultipartUploadParts",
                  "s3:PutObject"
                ],
                "Resource": [
                  "arn:aws:s3:::{{ minio_bucket_name }}/*"
                ],
                "Sid": ""
              }
            ]
          }
        dest: /tmp/minio_policy_{{ minio_bucket_name }}.json
      when:
        - minio_bucket_name != ""
        - minio_access_key != ""
        - minio_secret_key != ""

    - name: Create objectstore user policy
      command: "mc admin policy add minio readwrite-{{ minio_bucket_name }} /tmp/minio_policy_{{ minio_bucket_name }}.json"
      when:
        - minio_bucket_name != ""
        - minio_access_key != ""
        - minio_secret_key != ""

    - name: Remove objectstore user policy definition
      file:
        state: absent
        path: "/tmp/minio_policy_{{ minio_bucket_name }}.json"
      when:
        - minio_bucket_name != ""
        - minio_access_key != ""
        - minio_secret_key != ""

    - name: Create objectstore user
      command: "mc admin user add minio {{ minio_access_key }} {{ minio_secret_key }} readwrite-{{ minio_bucket_name }}"
      when:
        - minio_bucket_name != ""
        - minio_access_key != ""
        - minio_secret_key != ""

    - name: List objectstore buckets
      command: mc ls minio
      register: minio_buckets

    - name: Create objectstore bucket
      command: "mc mb minio/{{ minio_bucket_name }}"
      when:
        - minio_bucket_name != ""
        - minio_access_key != ""
        - minio_secret_key != ""
        - "' ' ~ minio_bucket_name ~ '/' not in minio_buckets.stdout"

    # This is set to enable unauthenticated download of all content contained in the bucket
    # via nginx proxy_pass directive.
    - name: Set bucket download policy
      command: "mc policy download minio/{{ minio_bucket_name }}"
      when:
        - minio_bucket_name != ""
        - minio_access_key != ""
        - minio_secret_key != ""

- hosts: $RABBITMQ_HOST
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    rabbitmq_vhost: "/{{ resource_prefix }}-vhost"
    rabbitmq_username: "{{ resource_prefix }}-user"
    rabbitmq_password: "$RABBITMQ_PASSWORD"

  tasks:
    - name: Create rabbitmq vhost
      rabbitmq_vhost:
        name: "{{ rabbitmq_vhost }}"
        state: present
      when:
        - rabbitmq_vhost != ""
        - rabbitmq_username != ""
        - rabbitmq_password != ""

    - name: Create rabbitmq user
      rabbitmq_user:
        user: "{{ rabbitmq_username }}"
        password: "{{ rabbitmq_password }}"
        permissions:
          - vhost: "{{ rabbitmq_vhost }}"
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present
      when:
        - rabbitmq_vhost != ""
        - rabbitmq_username != ""
        - rabbitmq_password != ""

- hosts: manager*:worker*
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add docker compose file
      copy:
        src: "{{ compose_file }}"
        dest: "{{ compose_file }}"

    - name: Add environments file
      template:
        src: templates/env
        dest: .env

    - name: Log in to private gitlab docker container registry
      docker_login:
        username: gitlab-ci-token
        password: "$CI_BUILD_TOKEN"
        registry: $CI_REGISTRY
        reauthorize: yes

    - name: Pull all images
      shell: docker-compose -f {{ compose_file }} pull
      args:
        executable: /bin/bash

    - name: Remove docker compose file
      file:
        state: absent
        path: "{{ compose_file }}"

    - name: Remove docker env file
      file:
        state: absent
        path: ".env"

- hosts: manager0
  remote_user: admin
  become: yes
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
    postdeploy_image: "$POSTDEPLOY_IMAGE"
    postdeploy_command: "$POSTDEPLOY_COMMAND"
    services_format_string: !unsafe "{{.Replicas}}"

  tasks:
    - name: Add docker compose file
      copy:
        src: "{{ compose_file }}"
        dest: "{{ compose_file }}"

    - name: Add environments file
      template:
        src: templates/env
        dest: .env

    - name: Deploy docker stack
      shell: docker stack deploy -c <(docker-compose -f {{ compose_file }} config) {{ resource_prefix }}
      args:
        executable: /bin/bash

    - name: Wait for all stack services to have replicated tasks
      command: "docker stack services {{ resource_prefix }} --format '{{ services_format_string }}'"
      register: cmd_res
      retries: 30
      delay: 2
      until: cmd_res.stdout_lines | reject('search','^(?!0)') | list | count == 0

    - name: Execute post deploy
      shell: >
        docker pull {{ postdeploy_image }};
        docker run --env-file .env
        --network={{ resource_prefix }}_default
        --add-host=postgres0:{{ hostvars['postgres0'].private_network_ip }}
        --add-host=minio0:{{ hostvars['minio0'].private_network_ip }}
        --add-host=rabbitmq0:{{ hostvars['rabbitmq0'].private_network_ip }}
        --rm
        -ti
        {{ postdeploy_image }}
        {{ postdeploy_command }}
      register: post_deploy

    - debug:
        var: post_deploy.stdout_lines

    - debug:
        var: post_deploy.stderr_lines

    - name: Remove docker compose file
      file:
        state: absent
        path: "{{ compose_file }}"

    - name: Remove docker env file
      file:
        state: absent
        path: ".env"