variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  STACK_NAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker login --username gitlab-ci-token --password $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose --file docker-compose-build.yml build --pull
    - docker-compose --file docker-compose-build.yml push

staging:
  stage: deploy
  image: python:3.7-slim
  script:
    - apt-get -yy update && apt-get install -y openssh-client
    - pip install ansible
    - mkdir keys
    - echo $QA_CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY > keys/id_rsa
    - chmod 700 keys/id_rsa
    - ansible-playbook -i $QA_CLUSTER_IP, --extra-vars "ansible_sudo_pass=$QA_CLUSTER_ADMIN_USER_PASSWORD ci_job_token=$CI_JOB_TOKEN ci_registry=$CI_REGISTRY stack_name=$STACK_NAME" deploy.yml
