stages:
  - build
  - deploy

variables:
  CI_PROJECT_REGISTRY: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  QA_COMPOSE_FILE: docker-compose.yml
  STAGING_COMPOSE_FILE: docker-compose.yml
  POSTDEPLOY_IMAGE: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/workspace:$CI_COMMIT_REF_SLUG
  PRODUCTION_COMPOSE_FILE: docker-compose.yml
  POSTDEPLOY_COMMAND_QA: ./docker/commands/post_deploy_qa.sh
  POSTDEPLOY_COMMAND_STAGING: ./docker/commands/post_deploy_staging.sh
  POSTDEPLOY_COMMAND_PRODUCTION: ./docker/commands/post_deploy_production.sh

build_master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/build.sh
    - chmod +x build.sh
    - ./build.sh
  only:
    - master
  except:
    - tags


build_qa:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/build.sh
    - chmod +x build.sh
    - ./build.sh
  only:
    - web
  except:
    - master
    - develop
    - tags


deploy_qa:
  stage: deploy
  image: python:3.7-slim
  variables:
    POSTDEPLOY_COMMAND: $POSTDEPLOY_COMMAND_QA
    STAGE: qa
    RESOURCE_PREFIX: unomena-qa-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    STACK_HOSTNAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.qa.cluster.unomena.net
    CLUSTER_IP: $INTERNAL_CLUSTER_IP
    CLUSTER_ADMIN_USER_PASSWORD: $INTERNAL_CLUSTER_ADMIN_USER_PASSWORD
    CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY_FILE: /tmp/keys/INTERNAL_CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY
  environment:
    name: qa/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.qa.cluster.unomena.net
    on_stop: stop_qa
  script:
    - apt-get -yy update && apt-get install -y wget
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/deploy.sh
    - chmod +x deploy.sh
    - ./deploy.sh
  only:
    - web
  except:
    - master
    - develop
    - tags


stop_qa:
  stage: deploy
  image: python:3.7-slim
  variables:
    STAGE: qa
    GIT_STRATEGY: none
    RESOURCE_PREFIX: unomena-qa-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG
    STACK_HOSTNAME: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.qa.cluster.unomena.net
    CLUSTER_IP: $INTERNAL_CLUSTER_IP
    CLUSTER_ADMIN_USER_PASSWORD: $INTERNAL_CLUSTER_ADMIN_USER_PASSWORD
    CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY_FILE: /tmp/keys/INTERNAL_CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY
  script:
    - apt-get -yy update && apt-get install -y openssh-client wget
    - pip install ansible
    - mkdir keys
    - cp $CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY_FILE keys/id_rsa
    - chmod 700 keys/id_rsa
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/destroy.yml
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/ansible.cfg
    - ansible-playbook -i $CLUSTER_IP, --extra-vars "ansible_sudo_pass=$CLUSTER_ADMIN_USER_PASSWORD ci_job_token=$CI_JOB_TOKEN ci_registry=$CI_REGISTRY resource_prefix=$RESOURCE_PREFIX stack_hostname=$STACK_HOSTNAME stage=$STAGE" destroy.yml
  environment:
    name: qa/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual
  only:
    - web
  except:
    - master
    - develop
    - tags


build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/build.sh
    - chmod +x build.sh
    - ./build.sh
  only:
    - tags
  except:
    - branches


staging:
  stage: deploy
  image: python:3.7-slim
  variables:
    POSTDEPLOY_COMMAND: $POSTDEPLOY_COMMAND_STAGING
    STAGE: staging
    RESOURCE_PREFIX: unomena-staging-$CI_PROJECT_NAME
    STACK_HOSTNAME: $CI_PROJECT_NAME.staging.cluster.unomena.net
    CLUSTER_IP: $INTERNAL_CLUSTER_IP
    CLUSTER_ADMIN_USER_PASSWORD: $INTERNAL_CLUSTER_ADMIN_USER_PASSWORD
    CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY_FILE: /tmp/keys/INTERNAL_CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY
  environment:
    name: staging
    url: https://$CI_PROJECT_NAME.staging.cluster.unomena.net
  script:
    - apt-get -yy update && apt-get install -y wget
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/deploy.sh
    - chmod +x deploy.sh
    - ./deploy.sh
  only:
    - tags
  except:
    - branches


production:
  stage: deploy
  image: python:3.7-slim
  variables:
    POSTDEPLOY_COMMAND: $POSTDEPLOY_COMMAND_PRODUCTION
    STAGE: production
    RESOURCE_PREFIX: unomena-production-$CI_PROJECT_NAME
    STACK_HOSTNAME: $PRODUCTION_STACK_HOSTNAME
    CLUSTER_IP: $PRODUCTION_CLUSTER_IP
    CLUSTER_ADMIN_USER_PASSWORD: $PRODUCTION_CLUSTER_ADMIN_USER_PASSWORD
    CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY_FILE: /tmp/keys/PRODUCTION_CLUSTER_ADMIN_USER_SSH_PRIVATE_KEY
  environment:
    name: production
    url: https://$PRODUCTION_STACK_HOSTNAME
  script:
    - apt-get -yy update && apt-get install -y wget
    - wget https://gitlab.unomena.net/unomenapublic/gitlab-pipeline/raw/master/deploy.sh
    - chmod +x deploy.sh
    - ./deploy.sh
  only:
    - tags
  except:
    - branches
  when: manual