---
- hosts: worker*
  any_errors_fatal: true
  remote_user: admin
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Create temporary deploy directory
      tempfile:
        state: directory
        suffix: deploy
      register: deploy_directory

    - name: Add docker compose file
      copy:
        src: "docker-compose.yml"
        dest: "{{ deploy_directory.path }}/docker-compose.yml"

    - name: Add docker compose override file
      copy:
        src: "docker-compose.override.yml"
        dest: "{{ deploy_directory.path }}/docker-compose.override.yml"

    - name: Add environments file
      template:
        src: templates/env
        dest: "{{ deploy_directory.path }}/.env"

    - name: Pull all images
      shell: docker-compose -f docker-compose.yml -f docker-compose.override.yml pull
      args:
        executable: /bin/bash
        chdir: "{{ deploy_directory.path }}"

    - name: Remove temporary deploy directory
      file:
        state: absent
        path: "{{ deploy_directory.path }}"