version: "3.4"

services:
{% for service in service_names.stdout_lines %}
  {{ service }}
      placement:
        constraints: [node.role == worker]
        constraints:
          - node.type == worker
{% endfor %}