version: "3.4"

services:
{% for service in service_names.stdout_lines %}
  {{ service }}:
    deploy:
      {% if service == 'celery-beat' and 'secondary' in inventory_hostname %}
replicas: 0
      {% endif %}
placement:
        constraints:
          - node.role == worker
          - node.labels.type == worker
    extra_hosts:
      - "postgres0:{{ hostvars['postgres0'].private_network_ip }}"
      - "minio0:{{ hostvars['minio0'].private_network_ip }}"
      - "rabbitmq0:{{ hostvars['rabbitmq0'].private_network_ip }}"
{% endfor %}
{% if stage == 'test' %}
  chrome:
    image: selenium/standalone-chrome-debug
{% endif %}